### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by adam-hanna** [Salompas/pytrendsdaily#2]
I'm getting an `invalid syntax` error in python 3.5

```python
>>> from pytrendsdaily import getDailyData

Traceback (most recent call last):

  File "/home/adam/.pyenv/ep-chan/lib/python3.5/site-packages/ipython-7.4.0-py3.5.egg/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-3-531ae61cfc18>", line 1, in <module>
    from pytrendsdaily import getDailyData

  File "/home/adam/.pyenv/learn-r/lib/python3.5/site-packages/pytrendsdaily/__init__.py", line 1, in <module>
    from .dailydata import getDailyData

  File "/home/adam/.pyenv/learn-r/lib/python3.5/site-packages/pytrendsdaily/dailydata.py", line 29
    return f"{start.strftime('%Y-%m-%d')} {stop.strftime('%Y-%m-%d')}"
                                                                     ^
SyntaxError: invalid syntax
```

And I get a different `invalid syntax` error in python 2.7:

```python
>>> from pytrendsdaily import getDailyData
File "/home/adam/.pyenv/learn-r/lib/python3.5/site-packages/pytrendsdaily/dailydata.py", line 10
    def getLastDateOfMonth(year: int, month: int) -> date:
                               ^
SyntaxError: invalid syntax
```

**Comment by adam-hanna** [comment]
Looks like I need python >= 3.6? Installing 3.7.3, now.

**Comment by adam-hanna** [comment]
Sorry, yes, I can clearly see from your [`setup.py`](https://github.com/Salompas/pytrendsdaily/blob/81177e88ecc3087a92d22e8bb0495dd4e18ef71a/setup.py#L19) that 3.6 is required. Closing the issue.

```python
...
classifiers=[
        "Programming Language :: Python :: 3.6",
...
```

**Comment by guilherme-salome** [comment]
Hey @adam-hanna thanks for checking the code. Indeed, Python 3.6+ is required due to the use of f-Strings. It should work if you change it to use the `.format` string formatting. I am not sure what would be necessary to make it work with Python 2.x since I haven't really ever coded in Python 2.x. Please let me know if you find any other issues!
